version: "3.9"
services:
  js-dtwb-backend:
    image: ghcr.io/jake-schuler/dtwb-backend:latest
    env_file:
      - .env
  js-dtwb-frontend:
    image: ghcr.io/jake-schuler/dtwb-frontend:latest
    ports:
      - "44481:4321"
    env_file:
      - .env